##
## EPITECH PROJECT, 2018
## zappy
## File description:
## .

all:
	cp launch.sh ../../zappy_ai
	@chmod +x ../../zappy_ai
.PHONY: all

clean:
	rm -f ../../zappy_ai
.PHONY: clean

fclean: clean
.PHONY: fclean
